ALTER TABLE IF EXISTS market_data_buckets
ADD COLUMN IF NOT EXISTS taker_buy_sell_ratio_avg DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS taker_buy_sell_ratio_close DOUBLE PRECISION NOT NULL DEFAULT 1;
