ALTER TABLE IF EXISTS trade_signals
ADD COLUMN IF NOT EXISTS market_regime VARCHAR(20) NOT NULL DEFAULT 'Balanced',
ADD COLUMN IF NOT EXISTS target_price_1 DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS target_price_2 DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS trailing_stop_price DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS tp1_hit BOOLEAN NOT NULL DEFAULT FALSE;
